# Generated by Django 4.1.5 on 2023-11-15 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mikey', '0002_register_is_active_register_is_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
