# Generated by Django 4.1.5 on 2023-11-19 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mikey', '0004_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='pseudo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pseudo_comments', to='mikey.register'),
        ),
    ]
